version: "3"
services:
  mongo:
    image: mongo
    container_name: truckpad-backend-test-mongo
    restart: always
    #ports:
    #  - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  app:
    build: .
    container_name: truckpad-backend-test-app
    restart: always
    ports:
      - 5000:5000
    #volumes:
    #  - .:/app
    depends_on:
      - mongo
    environment:
      FLASK_ENV: development
      FLASK_PORT: 5000
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_DB: terminal